### ISSUE TITLE
problems outputting midi to a file

### ISSUE THREAD

**Issue by dtenenba** [ideoforms/isobar#21]
Hi, first of all isobar is fantastic. I stumbled on it today and am just starting to explore the possibilities.

I took one of the examples and tweaked it a bit, then modified it further so that it would write its output to a midi file. It fails when I do that, but it works fine when outputting to the default midi device. 

I can convert the 00 hello world example to write to a file and it works just fine, but this more complex example has an issue when writing to a file. What am I doing wrong?

Here is the stack trace:

```
$ python 11.ex-lsystem-rhythm.py
[2022-02-10 16:09:08,249] Timeline: Scheduled new track (total tracks: 1)
[2022-02-10 16:09:08,249] Timeline: Starting
 *** Exception in Timeline thread: data byte must be int
Traceback (most recent call last):
  File "11.ex-lsystem-rhythm.py", line 63, in <module>
    timeline.run()
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/isobar/timeline/timeline.py", line 252, in run
    raise e
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/isobar/timeline/timeline.py", line 240, in run
    self.clock_source.run()
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/isobar/timeline/clock.py", line 86, in run
    self.clock_target.tick()
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/isobar/timeline/timeline.py", line 150, in tick
    track.tick()
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/isobar/timeline/track.py", line 124, in tick
    self.perform_event(self.current_event)
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/isobar/timeline/track.py", line 355, in perform_event
    self.output_device.note_on(note, amp, channel)
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/isobar/io/midifile/output.py", line 34, in note_on
    self.miditrack.append(Message('note_on', note=note, velocity=velocity, channel=channel, time=dt_ticks))
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/mido/messages/messages.py", line 114, in __init__
    check_msgdict(msgdict)
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/mido/messages/checks.py", line 99, in check_msgdict
    check_value(name, value)
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/mido/messages/checks.py", line 86, in check_value
    _CHECKS[name](value)
  File "/Users/dtenenba/envs/dev-hXAMQGPn/lib/python3.7/site-packages/mido/messages/checks.py", line 56, in check_data_byte
    raise TypeError('data byte must be int')
TypeError: data byte must be int
```

and here is the script - the line it fails on is the 2nd to last.

```python
#!/usr/bin/env python3

#------------------------------------------------------------------------
# isobar: ex-lsystem-rhythm
#
# Generates a rhythm line based on an L-system sprouting structure,
# sending output over MIDI.
#------------------------------------------------------------------------

import isobar as iso
import logging

logging.basicConfig(level=logging.INFO, format="[%(asctime)s] %(message)s")

#------------------------------------------------------------------------
# Generate a set of pitches based on an l-system, with recursive depth 4.
# symbols:
#  N = generate note node
#  + = transpose up one semitone
#  - = transpose down one semitone
#  [ = enter recursive branch
#  ] = leave recursive branch
#------------------------------------------------------------------------
notes = iso.PLSystem("N+[+N+N--N+N]+N[++N]", depth=4)
notes = iso.PDegree(notes, iso.Scale([0, 4, 6, 7, 10, 11]).shuffle())
# notes = iso.PNearestNoteInKey(notes, iso.Key("C", notes.scale))
min = min(notes)
notes.reset()
max = max(notes)
notes.reset()
notes = notes + 60 # optional...bassy without.
# scale to range of audible midi notes
notes = iso.PScaleLinLin(notes, min, max, 20, 127)
# notes = iso.PInt(notes)
# notes = iso.PDegree(notes, iso.Scale([0, 4, 6, 7, 10, 11]).shuffle())

# TODO - figure out if notes are still in the scale
# notes = notes + 60

#------------------------------------------------------------------------
# use another l-system to generate time intervals.
# take absolute values so that intervals are always positive.
#------------------------------------------------------------------------
times = iso.PLSystem("[N+[NN]-N+N]+N-N+N", depth=3)
times = iso.PAbs(iso.PDiff(times)) * 0.25

#------------------------------------------------------------------------
# ...and another l-system for amplitudes.
#------------------------------------------------------------------------
velocity = (iso.PLSystem("N+N[++N+N--N]-N[--N+N]") + iso.PWhite(-4, 4)) * 8
velocity = iso.PAbs(velocity)

output = iso.MidiFileOutputDevice("output.mid")

# timeline = iso.Timeline(120)#, output_device=output)
timeline = iso.Timeline(iso.MAX_CLOCK_RATE, output_device=output)
timeline.schedule({
    "note": notes,
    "amplitude": velocity,
    "duration": times
})
timeline.stop_when_done = True
timeline.run() # THIS is line 63 that the stack trace fails on
output.write()

```

**Comment by ideoforms** [comment]
Thanks for the comments and feedback! 
I have just taken a quick look at your example code, and the reason it's throwing an error is because the `note` pattern is generating float outputs: `PScaleLinLin` re-scales the output to a float type, which are not valid MIDI notes. This can be resolved by uncommenting the line in your code above:

```
notes = iso.PInt(notes)
```

This casts the notes to ints, which produce valid MIDI note values.

However, the current behaviour of the library is not very satisfactory - I think that either `MidiFileOutputDevice` should be more lenient with note values (casting to ints with a warning), or `PScaleLinLin` should output ints when all its inputs are ints. Or perhaps it could just raise a more informative exception. I will have a think and commit a fix.

**Comment by dtenenba** [comment]
Thanks, that works. 

On another topic, what's the best way to constrain pitches to be in the range of audible midi notes? (20..127) while also keeping them within the scale that I want to use?
