### ISSUE TITLE
Note C-1 is not managed by note_name_to_midi_note

### ISSUE THREAD

**Issue by piotereks** [ideoforms/isobar#41]
Note name for midi note 0 is C-1 and is maintained by util.
Inverted function breaks - see below
``` python
>>> import isobar as iso
>>> iso.midi_note_to_note_name(0)
'C-1'
>>> iso.note_name_to_midi_note('C-1')
Traceback (most recent call last):
  File "C:\Users\piote\PycharmProjects\isobar\isobar\util.py", line 63, in note_name_to_midi_note
    index = note_names.index([nameset for nameset in note_names if name in nameset][0])
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Users\piote\PycharmProjects\isobar\isobar\util.py", line 65, in note_name_to_midi_note

**Comment by ideoforms** [comment]
Now fixed courtesy of #41, thanks
